spring.application.name=globallive

# Base de datos H2
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:./data/globallive
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Admin password
admin.password=GlobalLive2026*

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
sendgrid.api.key=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